backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "investments"
    label: "Investments"
    folder: "src/pages/investments"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "investment-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: Banners,
              name: banners,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Text, name: text, widget: text },
                ],
            }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - {
              label: Stats,
              name: stats,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: text },
                  { label: Info, name: info, widget: string },
                ],
            }
          - {
              label: Services Intro,
              name: servicesIntro,
              widget: object,
              fields:
                [
                  {
                    label: Title,
                    name: title,
                    widget: object,
                    fields:
                      [
                        { label: Main phrase, name: mainPhrase, widget: text },
                        { label: Sub phrase, name: subPhrase, widget: text },
                      ],
                  },
                  { label: Description, name: description, widget: text },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: Projects,
              name: projectsIntro,
              widget: object,
              fields:
                [
                  {
                    label: Title,
                    name: title,
                    widget: object,
                    fields:
                      [
                        { label: Main phrase, name: mainPhrase, widget: text },
                        { label: Sub phrase, name: subPhrase, widget: text },
                      ],
                  },
                  { label: Description, name: description, widget: text },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: Trust badges,
              name: trustBadges,
              widget: list,
              fields: [{ label: Image, name: image, widget: image }],
            }
          - {
              label: Achievements,
              name: achievements,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: Companies,
              name: companies,
              widget: list,
              fields:
                [
                  { label: Name, name: name, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
      - file: "src/pages/about.md"
        label: "About Page"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - {
              label: Banner,
              name: banner,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: Overview,
              name: overview,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: Message,
              name: message,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Desctiption, name: description, widget: text },
                  { label: Image, name: image, widget: image },
                  { label: Signature, name: signature, widget: image },
                  { label: Full Name, name: fullName, widget: string },
                  { label: Designation, name: designation, widget: string },
                ],
            }
          - {
              label: Certification,
              name: certification,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { lable: Description, name: description, widget: text },
                  {
                    label: Badges,
                    name: badges,
                    widget: list,
                    fields: [{ label: Image, name: image, widget: image }],
                  },
                ],
            }
      - file: "src/pages/services.md"
        label: "Services Page"
        name: "services"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "services-page",
            }
          - {
              label: Banner,
              name: banner,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: Services,
              name: services,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Image, name: image, widget: image },
                  { label: Description, name: description, widget: text },
                ],
            }
      - file: "src/pages/projects.md"
        label: "Projects Page"
        name: "projects"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "projects-page",
            }
          - {
              label: Banner,
              name: banner,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: Projects,
              name: projects,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Image, name: image, widget: image },
                  { label: Client, name: client, widget: string },
                  { label: Year, name: year, widget: string },
                  { label: Type, name: type, widget: string },
                ],
            }
